CREATE TABLE IF NOT EXISTS tags
(id INTEGER PRIMARY KEY,
title TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS imagetags
(imageid INTEGER NOT NULL,
tagid INTEGER NOT NULL,
FOREIGN KEY (imageid) REFERENCES tags(id),
FOREIGN KEY (tagid) REFERENCES photos(id),
);
