// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/theloosygoose/goserver/internal/view/layout"
)

func Show() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1>This is the Admin View</h1><div class=\"container mx-auto\"><form class=\"flex-col justify-center align-center\" id=\"form\" hx-encoding=\"multipart/form-data\" hx-post=\"/addphoto\"><label for=\"name-input\">Name: <input type=\"text\" name=\"name\" id=\"name-input\"></label> <label for=\"location-input\">Location: <input type=\"text\" name=\"location\" id=\"location-input\"></label> <label for=\"description-input\">Description: <input type=\"text\" name=\"description\" id=\"description-input\"></label> <label for=\"imagefile-input\">Image File: <input type=\"file\" name=\"imageFile\" id=\"imagefile-input\"></label> <button class=\"p-6\" type=\"submit\">Upload <img src=\"dist/spinner.svg\" class=\"bg-primary stroke-primary fill-primary htmx-indicator\"></button> <progress id=\"progress\" value=\"0\" max=\"100\"></progress></form></div><script type=\"text/javascript\">\n    htmx.on('#form', \"htmx:xhr:progress\", function (evt) {\n        htmx.find('#progress').setAttribute('value', evt.detail.loaded / evt.detail.total * 100)\n    })\n</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
