// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package tools

import (
	"database/sql"
)

type Collection struct {
	ID   int64
	Name string
}

type ImageCollection struct {
	PhotoID      int64
	CollectionID int64
}

type Photo struct {
	ID          int64
	Name        string
	Location    string
	Date        sql.NullString
	Imagepath   string
	Description sql.NullString
	IHeight     sql.NullString
	IWidth      sql.NullString
}
